name: Download Assemblies to create override groups
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *' # Runs monthly on the 1st at midnight UTC
jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.9"
          activate-environment: grouping
          environment-file: environment.yaml
      - name: Run snakemake
        run: |
          snakemake --cores 1 clean
          snakemake --cores 10 next_update
        shell: bash -l {0} 
      - name: Upload to auspice
        run:
          snakemake --cores 1 upload
      - name: Commit and Push Results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull
          git add auspice/
          git commit -m "Update results from Snakemake run" || echo "No changes to commit"
          git push