if not config:
    configfile: "config/config.yaml"


def _get_all_targets(wildcards):
    # Default targets are the metadata TSV and sequences FASTA files
    all_targets = [
        "results/sequences.fasta",
        "results/metadata.tsv"
    ]

    return all_targets

rule all:
    input: _get_all_targets
    output: "../data/fetch/sequences.fasta", "../data/fetch/metadata.tsv"
    shell:
        """
        cp results/sequences.fasta ../data/fetch/
        cp results/metadata.tsv ../data/fetch/
        """


include: "workflow/rules/fetch_from_ncbi.smk"
include: "workflow/rules/curate.smk"
include: "workflow/rules/sort.smk"


